stages:
  - test

eslint:
  stage: test
  variables:
    NODE_VERSION: 14.17.0
  script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - nvm install $NODE_VERSION
    - source ~/.nvm/nvm.sh
    - npm ci
    - npm run lint